# Generated by Django 3.2 on 2021-07-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixar_studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisneyPlusBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dp_shorts_pics')),
                ('title_image', models.ImageField(upload_to='dp_shorts_pics')),
                ('shorts_title', models.CharField(max_length=50)),
                ('shorts_descriptions', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='TheatricalShorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='th_shorts_pics')),
                ('poster', models.ImageField(upload_to='th_shorts_pics')),
                ('title_image', models.ImageField(upload_to='th_shorts_pics')),
                ('secondary_images', models.ImageField(blank=True, upload_to='th_shorts_pics')),
                ('shorts_title', models.CharField(max_length=50)),
                ('shorts_descriptions', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='WebSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='website_pics')),
                ('logo', models.ImageField(upload_to='website_pics')),
                ('short_film_page_description', models.TextField(max_length=5000)),
            ],
        ),
    ]
