# Generated by Django 3.2 on 2021-07-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixar_studios', '0002_disneyplusblogs_theatricalshorts_websites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disneyplusblogs',
            name='title_image',
        ),
    ]
