# Generated by Django 3.2 on 2021-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixar_studios', '0003_remove_disneyplusblogs_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatricalshorts',
            name='image',
            field=models.ImageField(blank=True, upload_to='th_shorts_pics'),
        ),
    ]
